### ISSUE TITLE
ImportError: No module named ‘aiy.vision.leds’

### ISSUE THREAD

**Issue by rachelspykerman** [webrtcHacks/aiy_vision_web_server#2]
Hi,

I’m running into an error when trying to run the server.py script:

(env) pi@raspberrypi:~/AIY-projects-python $ sudo ../../../../env/bin/python3 server.py

Traceback (most recent call last):
File “server.py”, line 15, in
from aiy.vision.leds import Leds
ImportError: No module named ‘aiy.vision.leds’

It’s not able to find this module. Is there an install step I’m missing somewhere?

Thanks
Rachel

**Comment by chadwallacehart** [comment]
Do you know what aiy image you loaded? It looks like you are on an older one. They removed the virtual environment and changed some of the library references, including the LEDs. You should download and reflash your SD card with the latest image that has some improvements over the previous ones: https://dl.google.com/dl/aiyprojects/aiyprojects-latest.img.xz

My code is working with `aiyprojects-2018-02-21.img.xz`.

The old source under the virtual environment use to be:
`aiy._drivers._rgbled import PrivacyLED`

That module just illuminates the privacy LED, so worst case you can comment it out if that is the only thing that is giving you trouble and you don’t care about the light.

I answered the same on webrtcHacks too.

**Comment by rachelspykerman** [comment]
That solved the problem, thank you!
