### ISSUE TITLE
Annotation lag

### ISSUE THREAD

**Issue by julianoes** [webrtcHacks/aiy_vision_web_server#3]
First up, thanks a lot for the tutorial and code repo! That's very nice to get ~you~ me started.

I tried out the face example and it works correctly for a few seconds. Then the stream seems to lag behind the annotations. Basically, the annotations keep up with realtime but the stream is too slow and eventually freezes.

When I try to exit `server.py` it gets stuck at `exiting...`.
When I hit Ctrl+C again, I get:
```
^Cexiting...
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

After that, `uv4l` is still running, so I can't restart the server:
```
ps aux | grep uv4l
root       227 51.0 54.9 215872 208140 ?       SLsl 07:56   3:53 /usr/bin/uv4l -f -k --sched-fifo --mem-lock --config-file=/etc/uv4l/uv4l-raspidisp.conf --driver raspidisp --driver-config-file=/etc/uv4l/uv4l-raspidisp.conf --server-option=--editable-config-file=/etc/uv4l/uv4l-raspidisp.conf
root       233  0.1  2.2 101636  8432 ?        Ssl  07:56   0:00 /usr/bin/uv4l -f -k --sched-fifo --mem-lock --config-file=/etc/uv4l/uv4l-raspicam.conf --driver raspicam --driver-config-file=/etc/uv4l/uv4l-raspicam.conf --server-option=--editable-config-file=/etc/uv4l/uv4l-raspicam.conf
root       317  0.0  0.5   4416  2168 ?        Ss   07:56   0:00 /usr/bin/raspidisp_server /tmp/uv4l-raspidisp.socket
pi        1438  0.0  0.8   6568  3376 pts/0    S+   08:03   0:00 grep --color=auto uv4l
```

I also tried to start the server with `--framerate 5` but it behaved in the same way.
Note that I have recently done a `sudo apt-get dist-upgrade`.

Let me know if there is something I should try out, or you need additional info.

**Comment by julianoes** [comment]
Ok, so I tried with: `--framerate 10 --hres 640 --vres 480` and the stream kept up this time but the annotations are lagging behind until the point where the JSON output in the cose seems to stop even though my face should still get detected.

`htop -d 30` showed that CPU went to around 95% once it was running, and swap was filled to 57M as well.

The screenshot is taken at the time when the annotations are lagging but the stream still works.

![selection_029](https://user-images.githubusercontent.com/1419688/40935219-ac008cb0-6837-11e8-89f3-797a28aa22c8.png)

**Comment by chadwallacehart** [comment]
@julianoes - Luca from UV4L fixed the issue. Can you try doing:
```
sudo apt-get install --reinstall uv4l uv4l-webrtc-armv6 uv4l-raspidisp uv4l-raspidisp-extras
``` 
And then running it again?

**Comment by julianoes** [comment]
Sorry for the delay, I was on holiday.

So after a `sudo apt-get update and sudo apt-get dist-upgrade` I tried again and now the video stream is garbled in Firefox as well as Chromium, however, the tracking seemed to hold up, and also the garbled picture kept changing without delay.

![aiy vision detection view and annotation - chromium_032_cropped](https://user-images.githubusercontent.com/1419688/41933558-8ebd004e-7984-11e8-83ac-65e5094e1e5a.png)

Also, after about a minute it crashed:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 137, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, buf)
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 149, in run_inference
    for result in inference.run():
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 76, in run
    yield self._engine.camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 257, in camera_inference
    return self._communicate(request).inference_result
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 152, in transact
    raise SpicommInternalError
aiy._drivers._spicomm.SpicommInternalError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 236, in run_inference
    print("Avg inference time: %s" % (sum(time_log)/len(time_log)))
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 87, in __exit__
    self.close()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 79, in close
    self._engine.stop_camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 263, in stop_camera_inference
    self._communicate(request)
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 189, in _communicate
    raise InferenceException(response.status.message)
aiy.vision.inference.InferenceException: StopCameraInference: Camera inference is not running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 236, in run_inference
    print("Avg inference time: %s" % (sum(time_log)/len(time_log)))
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 758, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 752, in close
    raise exc
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1995, in _control_callback
    "No data recevied from sensor. Check all connections, "
picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check all connections, including the SUNNY chip on the camera board
```

**Comment by chadwallacehart** [comment]
That is very strange. You sure your camera is ok? Do the normal AIY Vision demos work ok? Can you see the video stream ok if you plug into a monitor? Does it crash all the same if you are not running UV4L? 

I might try posting the crash info to the [AIY Github Issues](https://github.com/google/aiyprojects-raspbian/issues).

**Comment by julianoes** [comment]
@chadwallacehart ok I'll check that.

**Comment by siyer7881** [comment]
@chadwallacehart firstly thank you so much for your thorough work. Really appreciate it.

with regard to the garbled video stream, i too experienced it. after doing `sudo apt-get install --reinstall uv4l uv4l-webrtc-armv6 uv4l-raspidisp uv4l-raspidisp-extras` and using
 the optimizations (python server.py --framerate 10 --hres 640 --vres 480) and checking the same on the raspi-config helped fix it.

**Comment by chadwallacehart** [comment]
My suspicion is that:
1.  the uv4l is casing some conflict as it grabs the data from the screen, or 
2. the the AIY Vision Kit is causing some conflict with the PiCamera. 

Since @julianoes had an error that indicated the SPIcomm interface, I am leaning toward a Vision Kit issue which would be best addressed on their repo.

It should be possible to test both uv4l and the Vision Kit independently. With all the AIY Kit programs turned off, what happens if you just load up a HD YouTube video on the Pi Desktop and then do a  http://raspberrypi.local:8090 to view that screen from a remote browser? Can you replicate the issue that way? That would check CPU overload issues with UV4L.

**Comment by chadwallacehart** [comment]
I did some tests and discovered I am having the same garbled screen issues - I created a new issue to track this:  #5

**Comment by julianoes** [comment]
With latest updates and after restarting with a fresh SD card image, the annotations and the stream work fine, that's with 10 Hz, 640x480.

Thanks for the help!
